name: turismo_capachica
description: A new Flutter project for Turismo Capachica.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: # Normally versioned, e.g. ^8.1.3
  equatable: # e.g. ^2.0.5
  flutter_secure_storage: # e.g. ^9.0.0
  dio: # e.g. ^5.3.3
  intl: # e.g. ^0.18.1
  google_maps_flutter: # e.g. ^2.5.0
  cupertino_icons: # e.g. ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: # e.g. ^2.0.0

flutter:
  uses-material-design: true

